import type { CharacterPost, FaqItem, GalleryItem, Partner, PartyCharacter, PartyEvent } from './types';

/**
 * Event copy and ticket types for Xoral Party VOL. 08.
 * Remaining stock is overwritten at runtime from paid ticket sales.
 */
export const MOCK_EVENT: PartyEvent = {
  id: 'evt_vol_08',
  slug: 'vol-08',
  name: 'Xoral Party',
  volume: 'VOL. 08',
  tagline: 'ONE PARTY. TWO WORLDS.',
  subtagline: '30 September is going to be one of a kind. They get ready there. We get ready here. That night, both worlds connect.',
  description:
    'Inside the Xoral Universe, the characters are living their stories and counting down to the crossover. On 30 September, Xoral Party brings that celebration into our world at Ambiance, Ikeja.',
  startsAt: '2026-09-30T20:00:00+01:00',
  doorsOpenAt: '2026-09-30T18:00:00+01:00',
  endsAt: '2026-10-01T04:00:00+01:00',
  scheduleLabel: '6:00 PM Red Carpet · Party starts 8:00 PM',
  venue: 'Ambiance',
  address: 'Ikeja',
  city: 'Lagos',
  mapsUrl: 'https://maps.google.com/?q=Ambiance+Ikeja+Lagos',
  dressCode: 'Nightlife glam. No sportswear. Dress like you might be seen on both sides.',
  ageRequirement: '18+',
  heroArtwork: '/posters/xoral-hero.svg',
  saleOpensAt: '2026-08-12T10:00:00+01:00',
  saleClosesAt: '2026-09-30T17:00:00+01:00',
  isMock: false,
  ticketTypes: [
    {
      id: 'tt_early',
      name: 'Early Access',
      slug: 'early-access',
      pricing: {
        maleKobo: 1_000_000,
        femaleKobo: 700_000,
        femaleMultiKobo: 500_000,
      },
      currency: 'NGN',
      description: 'Guy ₦10,000 · Lady ₦7,000 · Ladies Duo ₦10,000 for 2 (₦5,000 each).',
      benefits: ['Entry from doors open', 'Priority queue', 'Event wristband'],
      capacity: 200,
      remaining: 200,
      maxPerCustomer: 4,
      saleStartsAt: '2026-08-12T10:00:00+01:00',
      saleEndsAt: '2026-09-15T23:59:00+01:00',
    },
    {
      id: 'tt_ga',
      name: 'General Admission',
      slug: 'general-admission',
      pricing: {
        maleKobo: 1_000_000,
        femaleKobo: 700_000,
        femaleMultiKobo: 500_000,
      },
      currency: 'NGN',
      description: 'Guy ₦10,000 · Lady ₦7,000 · Ladies Duo ₦10,000 for 2 (₦5,000 each).',
      benefits: ['Full venue access', 'Main room + outdoor terrace', 'Event wristband'],
      capacity: 800,
      remaining: 800,
      maxPerCustomer: 6,
      saleStartsAt: '2026-08-12T10:00:00+01:00',
      saleEndsAt: '2026-09-30T17:00:00+01:00',
    },
    {
      id: 'tt_vip',
      name: 'VIP',
      slug: 'vip',
      pricing: {
        maleKobo: 4_500_000,
        femaleKobo: 3_000_000,
        femaleMultiKobo: 2_100_000,
      },
      currency: 'NGN',
      description: 'Priority access and a quieter, better-dressed room.',
      benefits: ['VIP entrance', 'VIP lounge access', 'One welcome drink', 'Priority bar'],
      capacity: 120,
      remaining: 120,
      maxPerCustomer: 4,
      saleStartsAt: '2026-08-12T10:00:00+01:00',
      saleEndsAt: '2026-09-30T17:00:00+01:00',
    },
    {
      id: 'tt_table',
      name: 'Table',
      slug: 'table',
      pricing: {
        maleKobo: 25_000_000,
        femaleKobo: 17_500_000,
        femaleMultiKobo: 12_500_000,
      },
      currency: 'NGN',
      description: 'Premium table reservation for your people.',
      benefits: ['Reserved table (up to 6)', 'Host service', 'VIP entrance', 'Bottle service menu'],
      capacity: 24,
      remaining: 24,
      maxPerCustomer: 2,
      saleStartsAt: '2026-08-12T10:00:00+01:00',
      saleEndsAt: '2026-09-30T17:00:00+01:00',
    },
    {
      id: 'tt_group',
      name: 'Group Pass',
      slug: 'group-pass',
      pricing: {
        maleKobo: 6_000_000,
        femaleKobo: 4_000_000,
        femaleMultiKobo: 2_800_000,
      },
      currency: 'NGN',
      description: 'Four general admission tickets, one checkout. Guy and girl pack rates apply.',
      benefits: ['4× General Admission', 'Shared order', 'Group check-in lane'],
      capacity: 80,
      remaining: 80,
      maxPerCustomer: 2,
      saleStartsAt: '2026-08-12T10:00:00+01:00',
      saleEndsAt: '2026-09-30T17:00:00+01:00',
    },
  ],
};

export const PARTY_CHARACTERS: PartyCharacter[] = [
  {
    id: 'sandra-rosewood',
    slug: 'sandra-rosewood',
    name: 'Sandra Rosewood',
    role: 'The one who actually shows up on time',
    personality: 'Reserved, athletic, already dressing for the 30th.',
    image: '/avatars/sandra-rosewood.svg',
    quote: 'Outfit finally sorted. See you 30 September.',
  },
  {
    id: 'clark-sylvester',
    slug: 'clark-sylvester',
    name: 'Clark Sylvester',
    role: 'Says he is not staying long',
    personality: 'Charming, loud, never leaves early.',
    image: '/avatars/clark-sylvester.svg',
    quote: "I'm not staying long.",
  },
  {
    id: 'lora-adams',
    slug: 'lora-adams',
    name: 'Lora Adams',
    role: 'Reads the room before anyone else',
    personality: 'Tomboy edge, calm delivery, lethal taste.',
    image: '/avatars/lora-adams.svg',
    quote: 'We both know that\'s a lie.',
  },
  {
    id: 'nicolas-martinez',
    slug: 'nicolas-martinez',
    name: 'Nicolas Martinez',
    role: 'Arrives last. Looks like he planned it.',
    personality: 'Unapologetic, leather, emerald calm.',
    image: '/avatars/nicolas-martinez.svg',
    quote: 'Save me a corner. Not the middle.',
  },
  {
    id: 'fiona-matthew',
    slug: 'fiona-matthew',
    name: 'Fiona Matthew',
    role: 'Starts the night. Ends someone else\'s.',
    personality: 'Bold, charming, slightly dangerous.',
    image: '/avatars/fiona-matthew.svg',
    quote: 'If you\'re still deciding, you\'re already late.',
  },
  {
    id: 'spencer-hawk',
    slug: 'spencer-hawk',
    name: 'Spencer Hawk',
    role: 'The quiet one by the speakers',
    personality: 'Understated, deep voice, notices everything.',
    image: '/avatars/spencer-hawk.svg',
    quote: 'The mix for 30 September is already writing itself.',
  },
];

export const CHARACTER_POSTS: CharacterPost[] = [
  {
    id: 'post-1',
    characterId: 'sandra-rosewood',
    characterName: 'Sandra',
    characterImage: '/avatars/sandra-rosewood.svg',
    body: 'Outfit finally sorted. See you 30 September.',
    postedAt: '2026-08-18T16:12:00+01:00',
  },
  {
    id: 'post-2',
    characterId: 'clark-sylvester',
    characterName: 'Clark',
    characterImage: '/avatars/clark-sylvester.svg',
    body: "I'm not staying long.",
    postedAt: '2026-08-18T16:40:00+01:00',
  },
  {
    id: 'post-3',
    characterId: 'lora-adams',
    characterName: 'Lora',
    characterImage: '/avatars/lora-adams.svg',
    body: "We both know that's a lie.",
    postedAt: '2026-08-18T16:41:00+01:00',
  },
  {
    id: 'post-4',
    characterId: 'fiona-matthew',
    characterName: 'Fiona',
    characterImage: '/avatars/fiona-matthew.svg',
    body: 'If you\'re still deciding, you\'re already late.',
    postedAt: '2026-08-18T17:05:00+01:00',
  },
  {
    id: 'post-5',
    characterId: 'spencer-hawk',
    characterName: 'Spencer',
    characterImage: '/avatars/spencer-hawk.svg',
    body: 'The mix for 30 September is already writing itself.',
    postedAt: '2026-08-18T18:22:00+01:00',
  },
];

export const PARTY_FAQS: FaqItem[] = [
  {
    id: 'what',
    question: 'What is Xoral Party?',
    answer:
      'A nightlife experience by Xoral Studios on 30 September 2026 at Ambiance, Ikeja. Guests come for DJs, music, dancing, drinks, fashion and a genuinely great night. Screens, characters and story moments will connect that night to a party on the other side of the Xoral Universe. Party first. Universe second.',
  },
  {
    id: 'where',
    question: 'Where is the event?',
    answer: 'Ambiance, Ikeja, Lagos. Full address is on your ticket.',
  },
  {
    id: 'time',
    question: 'What time does it start?',
    answer: 'Red carpet is at 6:00 PM. The party starts at 8:00 PM. The night runs into the early hours.',
  },
  {
    id: 'wear',
    question: 'What should I wear?',
    answer: 'Nightlife glam. No sportswear. Dress like you might be seen on both sides.',
  },
  {
    id: 'door',
    question: 'Can I buy tickets at the door?',
    answer: 'Door sales are not guaranteed. If a category sells out online, it will not be available at the door.',
  },
  {
    id: 'transfer',
    question: 'Can I transfer my ticket?',
    answer: 'Name changes may be requested before doors open through the ticket page. The QR is unique and should not be shared.',
  },
  {
    id: 'refund',
    question: 'Can I get a refund?',
    answer: 'Tickets are generally non-refundable except where required by law or if the event is cancelled. See the refund policy.',
  },
  {
    id: 'qr',
    question: "What happens if my QR code doesn't work?",
    answer: 'Bring the email confirmation and a valid ID. Door staff can look up your order number and issue a replacement scan.',
  },
  {
    id: 'age',
    question: 'Is there an age restriction?',
    answer: 'Yes. 18+ with valid ID at the door. No exceptions.',
  },
  {
    id: 'table',
    question: 'Can I reserve a table?',
    answer: 'Yes. Choose the Table ticket. Packages include a reserved table for up to six guests.',
  },
];

export const PARTY_PARTNERS: Partner[] = [
  { id: 'p1', name: 'Ambiance', category: 'venue' },
  { id: 'p2', name: 'Night Pour', category: 'beverage' },
  { id: 'p3', name: 'After Hours Radio', category: 'media' },
  { id: 'p4', name: 'Atelier Row', category: 'fashion' },
  { id: 'p5', name: 'Night Ride', category: 'mobility' },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: 'g1', category: 'people', kind: 'photo', src: '/avatars/sandra-rosewood.svg', alt: 'Guest energy', orientation: 'vertical' },
  { id: 'g2', category: 'energy', kind: 'photo', src: '/avatars/clark-sylvester.svg', alt: 'The floor', orientation: 'horizontal' },
  { id: 'g3', category: 'fits', kind: 'photo', src: '/avatars/fiona-matthew.svg', alt: 'The fits', orientation: 'vertical' },
  { id: 'g4', category: 'moments', kind: 'photo', src: '/avatars/nicolas-martinez.svg', alt: 'A moment', orientation: 'horizontal' },
  { id: 'g5', category: 'people', kind: 'photo', src: '/avatars/lora-adams.svg', alt: 'The people', orientation: 'vertical' },
  { id: 'g6', category: 'energy', kind: 'photo', src: '/avatars/spencer-hawk.svg', alt: 'Speakers', orientation: 'vertical' },
  { id: 'g7', category: 'fits', kind: 'photo', src: '/avatars/sapphire-paggie.svg', alt: 'Look', orientation: 'horizontal' },
  { id: 'g8', category: 'moments', kind: 'photo', src: '/avatars/davis-blake.svg', alt: 'After hours', orientation: 'vertical' },
];
