import type { Character } from './types';
import { characterAvatar } from './media';

export const characters: Character[] = [
  {
    id: 'clara-christopher',
    slug: 'clara-christopher',
    name: 'Clara Christopher',
    gender: 'female',
    age: 22,
    nationality: 'American',
    height: "5'8",
    eyes: 'almond hooded blue eyes',
    hair: 'straight brown hair',
    personality: 'calm, nice, extroverted',
    style: 'sexy, slim, long straight legs, freckles',
    voice: 'girly calm',
    profession: 'model',
    skinColor: 'tanned white skin',
    image: characterAvatar('clara-christopher'),
    description: 'American model — calm, nice, and extroverted with a striking runway presence.',
  },
  {
    id: 'fiona-matthew',
    slug: 'fiona-matthew',
    name: 'Fiona Matthew',
    gender: 'female',
    nationality: 'American',
    height: "5'0",
    eyes: 'fox eyes green almond',
    hair: 'long dark brown hair',
    personality: 'charming, annoying, bold',
    style: 'casual and a bit sexy',
    voice: 'calm voice',
    profession: 'Actress',
    skinColor: 'black American',
    image: characterAvatar('fiona-matthew'),
    description: 'American actress known for charming, unpredictable performances.',
  },
  {
    id: 'layla-baker',
    slug: 'layla-baker',
    name: 'Layla Baker',
    gender: 'female',
    age: 22,
    nationality: 'American',
    height: "5'6",
    eyes: 'cat blue almond',
    hair: 'long dark brown hair',
    personality: 'reserved, cute',
    style: 'casual but sexy',
    voice: 'calm voice',
    profession: 'Actress',
    skinColor: 'black American',
    image: characterAvatar('layla-baker'),
    description: 'Reserved and cute American actress with a quietly magnetic screen presence.',
  },
  {
    id: 'lora-adams',
    slug: 'lora-adams',
    name: 'Lora Adams',
    gender: 'female',
    age: 22,
    nationality: 'Nigerian',
    height: "5'9",
    eyes: 'cat ash almond',
    hair: 'low cut',
    personality: 'reserved, cute, tomboy',
    style: 'casual but sexy, tomboy',
    voice: 'calm voice',
    profession: 'Actress',
    skinColor: 'caramel',
    image: characterAvatar('lora-adams'),
    description: 'Nigerian actress with a tomboy edge and calm, grounded delivery.',
  },
  {
    id: 'nnena-kasim',
    slug: 'nnena-kasim',
    name: 'Nnena Kasim',
    gender: 'female',
    age: 23,
    nationality: 'Nigerian',
    height: "5'7",
    eyes: 'fox eyes blue almond',
    hair: 'bald',
    personality: 'reserved, cute',
    style: 'casual but sexy',
    voice: 'calm voice',
    profession: 'chef',
    skinColor: 'caramel',
    image: characterAvatar('nnena-kasim'),
    description: 'Nigerian chef and performer with a distinctive look and calm charisma.',
  },
  {
    id: 'sandra-rosewood',
    slug: 'sandra-rosewood',
    name: 'Sandra Rosewood',
    gender: 'female',
    nationality: 'white American',
    height: "5'10",
    eyes: 'almond brown eyes',
    hair: 'ponytail',
    personality: 'cute, sexy, reserved, athletic',
    style: 'athletic, tall, slim, tennis-inspired',
    voice: 'calm voice',
    profession: 'Actress',
    skinColor: 'white American',
    image: characterAvatar('sandra-rosewood'),
    description: 'Athletic American performer with a reserved, elegant on-screen energy.',
  },
  {
    id: 'sapphire-paggie',
    slug: 'sapphire-paggie',
    name: 'Sapphire Paggie',
    gender: 'female',
    nationality: 'Spanish',
    height: "5'0",
    eyes: 'fox blur almond',
    hair: 'short bulb hair',
    personality: 'cute, sexy, reserved',
    style: 'casual but sexy',
    voice: 'calm voice',
    profession: 'model',
    skinColor: 'caramel',
    image: characterAvatar('sapphire-paggie'),
    description: 'Spanish model with a calm voice and striking, reserved allure.',
  },
  {
    id: 'cho-ichiro',
    slug: 'cho-ichiro',
    name: 'Cho Ichiro',
    gender: 'male',
    age: 28,
    nationality: 'Asian American',
    height: "5'4",
    eyes: 'ash almond',
    hair: 'asian hair',
    personality: 'reserved, cute',
    style: 'casual but sexy',
    voice: 'calm voice',
    profession: 'tech person',
    skinColor: 'white',
    image: characterAvatar('cho-ichiro'),
    description: 'Asian American tech specialist who brings quiet precision to every role.',
  },
  {
    id: 'clark-sylvester',
    slug: 'clark-sylvester',
    name: 'Clark Sylvester',
    gender: 'male',
    nationality: 'Canadian',
    height: "6'3",
    eyes: 'fox eyes green emerald pupils',
    hair: 'curly dark brown',
    personality: 'charming, annoying, confident',
    style: 'sweatshirts and pants',
    voice: 'deep calm voice',
    profession: 'Actor',
    skinColor: 'white',
    image: characterAvatar('clark-sylvester'),
    description: 'Canadian actor with a deep calm voice and bold, charismatic energy.',
  },
  {
    id: 'davis-blake',
    slug: 'davis-blake',
    name: 'Davis Blake',
    gender: 'male',
    age: 25,
    nationality: 'Italian',
    height: "6'2",
    eyes: 'round eyes',
    hair: 'dark blond hair',
    personality: 'soft boy, foodie, ladies man',
    style: 'black casual',
    voice: 'soft calm voice',
    profession: 'producer',
    skinColor: 'olive',
    image: characterAvatar('davis-blake'),
    description: 'Italian producer with a soft, warm presence and foodie charm.',
  },
  {
    id: 'davids-valentino',
    slug: 'davids-valentino',
    name: "David's Valentino",
    gender: 'male',
    age: 22,
    nationality: 'Italian',
    height: "6'2",
    eyes: 'grey fox eyes',
    hair: 'dark blond hair',
    personality: 'soft boy',
    style: 'black shirt',
    voice: 'soft calm voice',
    profession: 'musician',
    skinColor: 'white',
    image: characterAvatar('davids-valentino'),
    description: 'Italian musician with grey fox eyes and a soft, romantic screen aura.',
  },
  {
    id: 'henry-uchenna',
    slug: 'henry-uchenna',
    name: 'Henry Uchenna',
    gender: 'male',
    age: 17,
    nationality: 'Nigerian American',
    height: "5'0",
    eyes: 'ash almond',
    hair: 'white guy hair',
    personality: 'reserved, cute',
    style: 'cute',
    voice: 'teenage voice',
    profession: 'Actor',
    skinColor: 'Nigerian American',
    image: characterAvatar('henry-uchenna'),
    description: 'Young Nigerian American actor with a reserved, cute teenage voice.',
  },
  {
    id: 'nicolas-martinez',
    slug: 'nicolas-martinez',
    name: 'Nicolas Martinez',
    gender: 'male',
    age: 22,
    nationality: 'Spanish',
    height: "6'2",
    eyes: 'emerald green eyes',
    hair: 'dark',
    personality: 'calm, unapologetic biker',
    style: 'leather jacket and white polo',
    voice: 'soft calm voice',
    profession: 'Actor',
    skinColor: 'caramel skin',
    image: characterAvatar('nicolas-martinez'),
    description: 'Spanish actor and calm biker with emerald green eyes and cool intensity.',
  },
  {
    id: 'spencer-hawk',
    slug: 'spencer-hawk',
    name: 'Spencer Hawk',
    gender: 'male',
    age: 24,
    nationality: 'Nigerian American',
    height: "6'0",
    eyes: 'ash almond',
    hair: 'low cut',
    personality: 'reserved, cute',
    style: 'casual but sexy',
    voice: 'calm deep voice',
    profession: 'actor',
    skinColor: 'black american',
    image: characterAvatar('spencer-hawk'),
    description: 'Nigerian American actor with a calm deep voice and understated charm.',
  },
];

export function getCharacterBySlug(slug: string) {
  return characters.find((character) => character.slug === slug);
}

export function getCharacterById(id: string) {
  return characters.find((character) => character.id === id);
}
